### PR TITLE
Build command

### LINKED ISSUE #132: Add a "build" command to the CLI
This would let users publish Sketchbook (with their custom config) to a website.

### PR DESCRIPTION
**Pull request by haydn**
This PR adds the `sketchbook build` command to the CLI. The `sketchbook build` command creates a new directory (`./sketchbook-build` by default) and generates out a static (read-only) version of the app using the specified design file.

I've also added are these command for testing the CLI in this project:

- `yarn preview:init`
- `yarn preview:start`
- `yarn preview:build`
- `yarn preview:help`

Note: You'll need to run `yarn build` before running any of the above commands and you'll need to remove the generated `preview` directory to rerun the `preview:init` command.

I've also updated the Vercel config to create and deploy the preview build:

```
yarn build && yarn preview:init && yarn preview:build
```

To test I've published a new `dev` version (`0.3.0-4`) and updated the website repo to use it:

https://github.com/sketchbook-js/website/blob/main/package.json#L10-L11

To install into your own project:

```
yarn add -D @sketchbook-js/sketchbook@dev
```

Closes #132.

### CODE REVIEW

**Comment by Mxchaeltrxn** [comment]
Issues:
Running `yarn start` and `yarn preview:start` (after running `yarn build && yarn preview:build && yarn preview:init`) both show me an empty page when going to `localhost:3000`. I think the commands aren't doing the same thing as well:
```js
    "preview:start": "node cli/index.js start -c preview/config.js preview/example.json",
    "start": "node scripts/start",
```

This is what I get when I run `yarn start`:
```sh
❯ yarn start
yarn run v1.22.10
$ node scripts/start

Canvas Build
> Process started: 16696

Editor Build
> Process started: 16697

Server
> Process started: 16698

Server
> Using config: /Users/michaeltran/Documents/10-19_software_development/10_projects/10.02_sketchbook/public/config.js
> 

Server
> Editing design: /Users/michaeltran/Documents/10-19_software_development/10_projects/10.02_sketchbook/example.json
> 

Server
> Sketchbook started:
> 
>   http://localhost:3000
> 
> 

Canvas Build
> 
> webpack is watching the files…
> 
> 

Editor Build
> 
> webpack is watching the files…
> 
> 

Canvas Build
> Hash: d5273bbac1182af1ed61
> Version: webpack 4.46.0
> Time: 530ms
> Built at: 05/09/2021 3:07:20 PM
>    Asset      Size  Chunks             Chunk Names
> index.js  4.18 KiB    main  [emitted]  main
> Entrypoint main = index.js
> [./src/canvas/index.js] 369 bytes {main} [built] [failed] [1 error]
> 
> ERROR in ./src/canvas/index.js 49:44
> Module parse failed: Unexpected token (49:44)
> File was processed with these loaders:
>  * ./node_modules/babel-loader/lib/index.js
> You may need an additional loader to handle the result of these loaders.
> |     render: config.components.find(({
> |       type
> >     }) => type === layer.component).render ?? defaultRender
> |   })).map(({
> |     id,
> 

Editor Build
> Hash: ef243e430bee489cd707
> Version: webpack 4.46.0
> Time: 1575ms
> Built at: 05/09/2021 3:07:21 PM
>    Asset      Size  Chunks             Chunk Names
> index.js  1010 KiB    main  [emitted]  main
> Entrypoint main = index.js
> [./src/Editor.js] 482 bytes {main} [built] [failed] [1 error]
> [./src/Reset.js] 1.83 KiB {main} [built]
> [./src/index.js] 399 bytes {main} [built]
>     + 17 hidden modules
> 
> ERROR in ./src/Editor.js 741:84
> Module parse failed: Unexpected token (741:84)
> File was processed with these loaders:
>  * ./node_modules/babel-loader/lib/index.js
> You may need an additional loader to handle the result of these loaders.
> |             type: "SketchbookComponent",
> |             component: component.type,
> >             name: (initial === null || initial === void 0 ? void 0 : initial.name) ?? component.type,
> |             x1: -viewport.x,
> |             y1: -viewport.y,
>  @ ./src/index.js 3:0-30 7:156-162
> 
```
Are you having the same issues? It seems like a webpack issue so I didn't look too deeply into it.

I tested it in a sample app and it worked fine and the other preview commands seem to look fine. Code seems good to me as well.

**Comment by haydn** [comment]
Hmm… that's odd. There are no changes in this PR to the start script, webpack config or the dependencies, so I'm not sure what could be going on there. 🤔

Does the `master` branch work for you? Have you done a `yarn install` on this branch? I'm guessing something is up with your dependencies.

I'm not in front of my computer right now, but I'll have a play around later on and see if I can reproduce this.

**Comment by Mxchaeltrxn** [comment]
That seems to have fixed the problem. Ah I tried on master branch but I didn't update my dependencies after pulling the code so it didn't work there either.

They both seem to work now with no issues.

**Comment by haydn** [comment]
@Mxchaeltrxn Excellent! Thanks for testing.

**Pull request merged**
